sudo: required

addons:
  postgresql: "9.3"
  apt:
    packages:
    - postgresql-server-dev-9.3

services:
- postgresql

language: python

virtualenv:
  system_site_packages: true

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"


before_install:
  - sudo make -C external/q3c install
  - psql -c "\du" -U postgres | cat
  - psql -l | cat
  - psql -c "create database $USER;" -U postgres | cat
install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install --upgrade pip
  - pip install tox
  - pip freeze
script:
  - cd ${TRAVIS_BUILD_DIR}
  - tox
